apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      googlecloud:
        project: <your-project-id>
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [googlecloud]
