apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <filter kubernetes.**>
      @type record_transformer
      ...
    </filter>

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  template:
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
