apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: global-ingress
spec:
  rules:
    - host: my-app.com
      http:
        paths:
          - path: /
            backend:
              serviceName: my-service
              servicePort: 80
