apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
        - name: app-container
          image: app-image:latest
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
