apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: configmap-app
    spec:
      containers:
        - name: app-container
          image: app-image:latest
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOG_LEVEL
