apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: db-secret
spec:
  backendType: vault
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/database
        property: password
  target:
    name: db-credentials
